import streamlit as st
import requests

BASE_URL = 'http://localhost:8000'

st.set_page_config(
    page_title='Travel Planner Agentic Application',
    layout='centered',
    initial_sidebar_state='expanded'
)

st.title('Travel Planner Agentic Application ')

# Initialize chat history
if 'messages' not in st.session_state:
    st.session_state['messages'] = []


st.header('How can I help you in planning a trip? Let me know where do you want to visit.')

# Chat Input Box at bottom
with st.form():
    user_input = st.text_input( 'User Input', placeholder='eg. Plan a trip to goa for 5 days.' )
    submit_button = st.form_submit_button( 'Send' )

if submit_button and user_input.strip():
    try:

        # Show your message
        # Show thinking spinner while background process
        with st.spinner('Bot is thinking'):
            payload = { 'question': user_input }
            response = requests.post( BASE_URL + '/query', json=payload )

        if response.status_code == 200:
            answer = response.json().get('answer', 'No answer returned.')
            markdown_content = f"""AI Travel Plan
            {answer}

            'This travel plan was generated by AI. Please verify all information, especially prices'
            """

            st.markdown(markdown_content)
        
        else:
            st.error( 'Bot unable to respond: ', response.text )

    except Exception as e:
        raise "The response failed due to {e}"