import React, { useState, useRef, useEffect } from 'react';
import axios from 'axios';
import ReactMarkdown from 'react-markdown';
import { Send, Compass } from 'lucide-react';

const App = () => {
  const [messages, setMessages] = useState([
    {
      role: 'ai',
      content: "Hello! I am VoyageAI, your premium travel planner. Where would you like to travel today?",
    }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = async (e) => {
    e.preventDefault();
    if (!input.trim()) return;

    const userMessage = { role: 'user', content: input };
    setMessages((prev) => [...prev, userMessage]);
    setInput('');
    setIsLoading(true);

    try {
      const response = await axios.post('http://localhost:8000/query', {
        query: userMessage.content,
      });

      if (response.status === 200) {
        const answer = response.data.answer || 'No answer returned.';
        setMessages((prev) => [
          ...prev,
          {
            role: 'ai',
            content: answer + "\n\n*This travel plan was generated by AI. Please verify all information, especially prices.*",
          },
        ]);
      } else {
        setMessages((prev) => [
          ...prev,
          { role: 'ai', content: `Error: ${response.data}` },
        ]);
      }
    } catch (error) {
      setMessages((prev) => [
        ...prev,
        { role: 'ai', content: `Request failed: ${error.message}` },
      ]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-screen bg-[#050505] text-[#e5e2e1] overflow-hidden font-['Inter']">
      {/* TopAppBar */}
      <header className="fixed top-0 w-full z-50 bg-[#121212]/40 backdrop-blur-xl border-b border-white/10 px-5 py-3 flex justify-between items-center h-16">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 flex items-center justify-center bg-gradient-to-br from-[#3b82f6] to-[#06b6d4] rounded-full">
             <Compass size={20} color="white" />
          </div>
          <h1 className="text-xl font-semibold tracking-tight">VoyageAI</h1>
        </div>
        <div className="flex items-center gap-4">
          {isLoading && <span className="text-sm text-[#06b6d4] animate-pulse">Agent typing...</span>}
        </div>
      </header>

      {/* Chat Area */}
      <div className="flex-1 overflow-y-auto px-5 py-6 mt-16 mb-24 custom-scrollbar">
        <div className="max-w-3xl mx-auto flex flex-col gap-6">
          {messages.map((msg, idx) => (
            <div
              key={idx}
              className={`flex flex-col gap-2 max-w-[85%] message-fade-in ${
                msg.role === 'user' ? 'self-end items-end' : 'self-start items-start'
              }`}
            >
              {msg.role === 'ai' && (
                <div className="flex items-center gap-2 mb-1 pl-1">
                  <div className="w-5 h-5 rounded-full bg-gradient-to-br from-[#3b82f6] to-[#06b6d4] flex items-center justify-center">
                    <Compass size={12} color="white" />
                  </div>
                  <span className="text-xs font-semibold tracking-wider text-[#c2c6d6] uppercase">Travel Agent</span>
                </div>
              )}
              
              <div
                className={`p-4 rounded-2xl ${
                  msg.role === 'user'
                    ? 'bg-gradient-to-br from-[#3b82f6] to-[#06b6d4] text-white rounded-tr-sm shadow-[0_0_20px_rgba(76,215,246,0.15)]'
                    : 'bg-[#121212]/60 backdrop-blur-md border border-white/10 rounded-tl-sm text-[#e5e2e1]'
                }`}
              >
                {msg.role === 'ai' ? (
                  <div className="prose prose-invert prose-sm max-w-none prose-headings:text-[#adc6ff] prose-a:text-[#4cd7f6]">
                    <ReactMarkdown>{msg.content}</ReactMarkdown>
                  </div>
                ) : (
                  <p className="text-[15px] leading-relaxed">{msg.content}</p>
                )}
              </div>
            </div>
          ))}
          <div ref={messagesEndRef} />
        </div>
      </div>

      {/* Input Area */}
      <div className="fixed bottom-0 w-full bg-[#121212]/80 backdrop-blur-xl border-t border-white/10 px-5 py-4">
        <div className="max-w-3xl mx-auto relative">
          <form onSubmit={handleSend} className="flex gap-2">
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Where to next?"
              className="w-full bg-[#131313] border border-white/10 rounded-full py-4 pl-6 pr-14 text-[15px] text-white placeholder-[#8c909f] focus:outline-none focus:border-[#4cd7f6] focus:ring-1 focus:ring-[#4cd7f6] transition-all"
              disabled={isLoading}
            />
            <button
              type="submit"
              disabled={isLoading || !input.trim()}
              className="absolute right-2 top-2 w-10 h-10 rounded-full bg-gradient-to-br from-[#3b82f6] to-[#06b6d4] flex items-center justify-center hover:opacity-90 transition-opacity disabled:opacity-50"
            >
              <Send size={18} color="white" />
            </button>
          </form>
        </div>
      </div>
    </div>
  );
};

export default App;
